### PR TITLE
Fix for wrong tiles because of different diagonal tile.

### PR DESCRIPTION
**Pull request by ufdada**
This fixes water and claimed tiles. Best seen on Asmodeus.

**Before:**
wrongtile-1
wrongtile-2

**After:**
watertile-r-1
watertile-r-2

### CODE REVIEW

**Comment by tonihele** [comment]
Thank god! I spent so much time on those when I made them. And today I saw this also and instant depression :)

**Comment by ufdada** [comment]
:) It took me some time to figure out. But after that it was pretty obvious.

**Comment by ufdada** [comment]
Hopefully also fixing your depression :D

**Comment by tonihele** [comment]
Yes, you are a life saver :+1:

**Pull request merged**
