### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by ufdada**
Fixed a typo (campaign instead of campaing) and converted the if else to switch cases

### CODE REVIEW

**Comment by tonihele** [comment]
Looks good. FYI, I'm currently trying to create the graphics options. To get rid of the JME one (branding) and add things like SSAO

**Comment by ufdada** [comment]
Sounds great :). I try to fix some things in the campaign menu (like camera, the arrows, some broken graphics)

**Comment by tonihele** [comment]
If you manage to get the camera right, I'll give you a gold medal :) I thought that I would implement the level camera things on the game state (to test & show) but maybe it is better to wait the proper trigger system implementation. But I think there is a good amount of the camera transitions to get it right on the main menu alone.

The campaign level selection I think is "broken" since there is no logic of campaign advancement. So everything is just laid out there. Especially the A & B & C levels + the "level" probably make them very broken. The animations & amount of "raising" on the levels is just reverse engineered by eye.

Do you use IRC etc? Or even Steam etc. It would make communicating easier if needed.

**Comment by ufdada** [comment]
Here is my steam profile: http://steamcommunity.com/profiles/76561197962486008/

**Pull request merged**
